# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Encoder EC11 — trigger via thread global
# Seleção do choice EC11_TRIGGER feita via .conf (não Kconfig.defconfig)
CONFIG_ZMK_BATTERY_REPORTING=y