# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Encoder EC11 — trigger via thread global
# Seleção do choice EC11_TRIGGER feita via .conf (não Kconfig.defconfig)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y